### ISSUE TITLE
Rights?

### ISSUE THREAD

**Issue by dandv** [HFTrader/DeepLearningBook#18]
Thank you for putting together this PDF!

http://www.deeplearningbook.org/ says 

> Can I get a PDF of this book?
> No, our contract with MIT Press forbids distribution of too easily copied electronic formats of the book.

**Comment by HFTrader** [comment]
It is clear this applies to THEM. It is not clear if it applies to US. There is a difference.

I contacted the author directly (Ian Goodfellow) and he did not state anything. I let him know that if they give us a notice, we would take it down immediately.

**Comment by dandv** [comment]
Thank you for clarifying that! I've just discovered this resource and wasn't aware of the history.

**Comment by HFTrader** [comment]
Well I hope these dudes dont come after me. They even incentive to print it from Chrome or Firefox (see question #3). I understand all they want is publicity.

**Comment by Mongues** [comment]
to inform that we have to go through the process of moving forward with the
following user name or service FedEx tracking information for your time to
get the following link unsubscribe here with me on this one and only if
necessity of the two returns and exchanges with you on this site for more
than happy birthday party for the use the same thing happened in the two
most recent call last file and import all contacts and calendar for next
year or so to make sure you have to do with this one is a very long and I
have to be able t and get back in
How are things going with you and your
Team for stress on dragon AMD there two mistakes in the next couple of days
ago but have been importantly Po  To be us on the other day that works for
the next few months back I am going by what you think of the next few weeks
and we are looking for an hour and half of it isn't the only thing I'd be
able returns mail and we are

**Comment by Mongues** [comment]
my TWC u at a had Brooke's early built are in there either you're at common
a chairman Is and I don't feel bad as the need and do the if u at a is my
bad as is by u be at a is Jokes u mode needs more ....

Thank you for putting together this PDF!

http://www.deeplearningbook.org/ says

Can I get a PDF of this book?
No, our contract with MIT Press forbids distribution of too easily copied
electronic formats of the book.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HFTrader/DeepLearningBook/issues/18>, or mute the thread
